import "./globals.css";

import type { Metadata } from "next";
import { Inter as InterFF } from "next/font/google";

import { DarkTheme } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Inter = InterFF({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased dark:bg-blue-500 bg-green-400 ${Inter.className}`}
      >
        <DarkTheme />
        {children}
      </body>
    </html>
  );
}
